### ISSUE TITLE
Not working HTTPS-Finder 0.87 in FF 22

### ISSUE THREAD

**Issue by Zaycoff** [kevinjacobs/HTTPS-Finder#14]
Not working HTTPS-Finder 0.87 in FF 22 (menu and item of interfaces working, but not finding and don't create new HTTPS rules).
Please, fix it :)

And, if possible, add russian locale for HTTPS-Finder.
This HTTPS-Finder with russian locale: http://forum.mozilla-russia.org/uploaded/https_finder-0.87-fx-ru-MOD.xpi
This only russian locale: http://forum.mozilla-russia.org/uploaded/https_finder-locale-ru-RU.zip

**Comment by kevinjacobs** [comment]
Thanks for the report - I know the issue with Fx22+ and will be working on a fix over the next few days.

**Comment by kevinjacobs** [comment]
Fixed version is here: https://code.google.com/p/https-finder/downloads/detail?name=httpsfinder_0.89.xpi (with your added ru-RU locale, thanks!)

Let me know if you see any other issues.
