### ISSUE TITLE
Palemoon

### ISSUE THREAD

**Issue by Mayurifag** [kevinjacobs/HTTPS-Finder#27]
Hello! Can you please add the support of you extension with Encrypted Web, the fork of HTTPS-Everywhere for Pale Moon? https://addons.palemoon.org/extensions/privacy-and-security/encrypted-web/

**Comment by TPS** [comment]
@Mayurifag I think, since the last commit (https://github.com/kevinjacobs/HTTPS-Finder/commit/cabb556fd339e95c03fb8f7491b511b7197ae6d3) is from April 2014, this is now officially abandoned, but feel free to fork & update for PM!  I would use it, myself! :+1:

**Comment by Mayurifag** [comment]
@TPS haha, yea, I'd fork this if I was able to do it, for sure!

**Comment by TPS** [comment]
@Mayurifag It seems more likely that official HTTPS Everywhere is more likely to get official support (@ least via some sort of more-compatible [fork](https://github.com/EFForg/https-everywhere/issues/1315#issuecomment-308462887) — that is, more compatible to both HTTPS Finder ___&___ current PM) than HTTPS Finder ever getting support for the now-evaporated Encrypted Web. 🤷
