### ISSUE TITLE
Doesn't work with latest stable Firefox

### ISSUE THREAD

**Issue by Drugoy** [kevinjacobs/HTTPS-Finder#7]
##

**Comment by JustMyGithub** [comment]
sad but true - just tested it using a clean new profile!

**Comment by LordJZ** [comment]
I can confirm this too.

**Comment by kevinjacobs** [comment]
Sorry I updated Google code but not here. This is due to the removal of E4X in Firefox 20+. I'm working on a updated version right now.

**Comment by kevinjacobs** [comment]
New version is here, tested good on Firefox 20+

https://code.google.com/p/https-finder/downloads/detail?name=HttpsFinder087.xpi

**Comment by Drugoy** [comment]
Why haven't you uploaded that version to AMO?
The bug I reported concerns latest stable version of Fx, which is 20, not 21.

**Comment by kevinjacobs** [comment]
Sorry, 20. 

I haven't uploaded it yet because I had limited time on Saturday to work on it, and wanted to continue testing for a couple days to make sure there were no other changes that I need to account for. 

It takes a week or two to get through the AMO review process anyway.
